# Autogenerated file
def render(emp_dict):
    yield """

<!DOCTYPE html>
<html>

<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
<style>

th, td """
    yield """{ color:white; 
}

body """
    yield """{ color:white; background-color:black;
}
</style>

<body>
<h1>Message Window</h1>
<table>
<thead>
<tr>
<th>UnixTime</th>
<th>Content</th>
</tr>
</thead>
<tbody>

"""
    for key , value in emp_dict.items():
        yield """
<tr>
<td>"""
        yield str(key)
        yield """ </td>
<td>"""
        yield str(value)
        yield """</td>
</tr>
"""
    yield """
</tbody>
</table>
<form method=\"POST\", onsubmit=\"getUnixTime()\">
<textarea id=\"textbox\" name=\"textbox\" rows=\"4\"></textarea>
<input type =\"hidden\" id=\"unixTime\", name=\"unixTime\"/>
<input type=\"submit\" name=\"submit\"/>
</form>

<script>
function getUnixTime() """
    yield """{
    var inst = Math.round((new Date()).getTime() / 1000);
    document.getElementById(\"unixTime\").value = inst;
    }
</script>

</body>
</html>

"""
