# Autogenerated file
def render(*a, **d):
    # Autogenerated file
    def render1(*a, **d):
        yield """<!DOCTYPE html>
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1\">
<style>
<html lang=\"en\">

table """
        yield """{
    width: 100%;
    color: white;
    border: 1px solid;
}


th, td """
        yield """{ 
        color:white;
        word-wrap: break-word;
}

body """
        yield """{ color:white; background-color:black;
}

.cursor-right """
        yield """{
   text-align: right;
}

.col_right """
        yield """{
   text-align: right;
}

.col_left """
        yield """{
   text-align: left;
}

.time_left """
        yield """{
   text-align: left;
   font-size: 8px;
}


ul """
        yield """{
  list-style-type: none;c
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li """
        yield """{
  float: left;
}

li a """
        yield """{
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover:not(.active) """
        yield """{
  background-color: #111;
}

.active """
        yield """{
  background-color: #04AA6D;
}
</style>

<head>
    <meta charset=\"UTF-8\">
    <title>Lora_Messenger_Webapp</title>
</head>

<ul>
  <li><a href=\"/new_convo\">New_Convo</a></li>
  <li><a href=\"/\">Prev_Contacts</a></li>
  <li><a href=\"/\">Settings</a></li>
</ul>

"""
    yield from render1()
    yield """

<body>
<h1>Sent to Address:</h1>

<div>Must be an integer between 0 and 255></div>
<div>using 255 will broadcast to all addresses in range</div>
<form method=\"POST\">
<input type =\"text\" id=\"new_address\", name=\"new_address\"/>
<input type=\"submit\" name=\"submit\"/><br>
</form>



</body>
</html>"""
